name: "certviewer-CI"

on:
  push:
    branches: ['**']
  pull_request:
  release:
    types: [published]

env:
  NON_INTERACTIVE: 1

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [ { name: Release, fody: true }, { name: Debug, fody: false } ]
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
      - uses: nuget/setup-nuget@v2
      - run: nuget restore CertViewer.sln
      - run: msbuild /t:Rebuild /p:Configuration=${{ matrix.configuration.name }} /p:Platform="Any CPU" /p:EnableCosturaFody="${{ matrix.configuration.fody }}" CertViewer.sln
      - uses: actions/upload-artifact@v4
        with:
          name: certviewer.${{ matrix.configuration.name }}
          path: bin\${{ matrix.configuration.name }}\
